kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rwo-pv-claim
spec:
  storageClassName: default-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
